<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>LQ.DatabaseHelper</RootNamespace>
    <AssemblyName>LDatabaseHelper</AssemblyName>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FreeSql" Version="3.5.311" />
    <PackageReference Include="FreeSql.DbContext" Version="3.5.311" />
    <PackageReference Include="FreeSql.Extensions.JsonMap.STJ" Version="3.5.305" />
    <PackageReference Include="FreeSql.Provider.Sqlite" Version="3.5.311" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LDatabaseAnalyser\LDatabaseAnalyser.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
